'use client';
import { useEffect,useRef,useState } from 'react';
import { Plus,ArrowUpRight,ArrowDownToLine,RotateCcw,Check,Archive,RefreshCw,Columns3,ShieldCheck,Clock3,Link2,Repeat2 } from 'lucide-react';
import {TaskDetails,type TaskDetailsHandle} from './task-details';
import {AccessDialog} from './access-dialog';
import {validateBackup} from '@/lib/backup';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Toaster,toast } from 'sonner';
import { statuses,labels,inputOf,type Task,type TaskInput } from '@/lib/model';
const blank:TaskInput={title:'',category:'General',status:'ToDo',nextAction:'',attention:'none',blocker:'',dueDate:null,dueTime:null,timezone:null,recurrence:null,sourceUrl:'',sourceChatId:'',sourceVerifiedAt:null,evidenceNote:'',resources:[],checklist:[],sample:false};
async function api(name:string,args:any={}):Promise<any>{const r=await fetch('/api/board',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,args})});let data:any;try{data=await r.json()}catch{throw new Error('Could not reach task storage. Your draft is still here.')};if(!r.ok)throw new Error(data.message||'Request failed');return data}
function Choice({label,value,options,onChange}:{label:string,value:string,options:[string,string][],onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full h-10"><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label>}
function Field({label,value,onChange,multiline=false,type='text',placeholder='',required=false}:{label:string,value:string,onChange:(v:string)=>void,multiline?:boolean,type?:string,placeholder?:string,required?:boolean}){return <label className="field"><span>{label}</span>{multiline?<textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} rows={3}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} required={required}/>}</label>}
export default function Board({canWrite=true,canManageAccess=false}:{canWrite?:boolean,canManageAccess?:boolean}){
const [tasks,setTasks]=useState<Task[]>([]),[archived,setArchived]=useState<Task[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[view,setView]=useState('active');
const [open,setOpen]=useState(false),[selected,setSelected]=useState<Task|null>(null),[draft,setDraft]=useState<TaskInput>(blank),[history,setHistory]=useState<any[]>([]),[editError,setEditError]=useState('');
const [accessOpen,setAccessOpen]=useState(false);
const [recovery,setRecovery]=useState(false),[importData,setImportData]=useState<any>(null),[preview,setPreview]=useState<any>(null),[snapshots,setSnapshots]=useState<any[]>([]),[recoveryError,setRecoveryError]=useState('');
const detailRef=useRef<TaskDetailsHandle>(null),returnFocus=useRef<HTMLElement|null>(null);
const retryKeys=useRef(new Map<string,string>()),fileRef=useRef<HTMLInputElement>(null);
async function refresh(){const [a,b]=await Promise.all([api('list_tasks'),api('list_tasks',{archived:true})]);setTasks(a.tasks);setArchived(b.tasks);setError('')}
function requestKey(name:string,args:any){const f=JSON.stringify({name,args});if(!retryKeys.current.has(f))retryKeys.current.set(f,crypto.randomUUID());return retryKeys.current.get(f)!}
async function mutation(name:string,args:any){return api(name,{...args,requestKey:requestKey(name,args)})}
useEffect(()=>{let alive=true;(async()=>{try{if(canWrite)await api('seed_samples');if(alive)await refresh()}catch(e){if(alive)setError((e as Error).message)}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[canWrite]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();for(const tool of [{name:'list_board_tasks',description:'Read saved task records from this private board.',schema:{type:'object',properties:{},additionalProperties:false},read:true,execute:async()=>api('list_tasks')},{name:'open_task_details',description:'Open the visible editor for one task; does not save changes.',schema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},read:true,execute:async(input:any)=>{if(!input||typeof input.id!=='string')throw new Error('Task ID required');if(detailRef.current&&!detailRef.current.canLeave())throw new Error('Unsaved draft is still open');returnFocus.current=document.activeElement as HTMLElement;setSelected({id:input.id} as Task);setOpen(true);return {openedTaskId:input.id}}}]){try{Promise.resolve(context.registerTool({name:tool.name,description:tool.description,inputSchema:tool.schema,annotations:{readOnlyHint:tool.read,untrustedContentHint:true},execute:tool.execute},{signal:controller.signal})).catch(()=>{})}catch{}}return()=>controller.abort()},[]);
function edit(t:Task){if(detailRef.current&&!detailRef.current.canLeave())return;returnFocus.current=document.activeElement as HTMLElement;setSelected(t);setOpen(true)}
function openAccess(){if(canManageAccess!==true||(detailRef.current&&!detailRef.current.canLeave()))return;returnFocus.current=document.activeElement as HTMLElement;setOpen(false);setAccessOpen(true)}
function create(){if(detailRef.current&&!detailRef.current.canLeave())return;returnFocus.current=document.activeElement as HTMLElement;setSelected(null);setOpen(true)}
function change(k:keyof TaskInput,v:any){setDraft(x=>({...x,[k]:v}))}
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setEditError('');try{const r=selected?await mutation('update_task',{id:selected.id,expectedRevision:selected.revision,patch:draft}):await mutation('create_task',{task:draft});await refresh();setSelected(r.task);setDraft(inputOf(r.task));setOpen(false);toast.success(selected?'Task saved':'Task created')}catch(e){setEditError((e as Error).message)}finally{setBusy(false)}}
async function action(name:string,t:Task){setBusy(true);setEditError('');try{const r=await mutation(name,{id:t.id,expectedRevision:t.revision});await refresh();setSelected(r.task);setDraft(inputOf(r.task));setOpen(false);toast.success(name==='complete_task'&&t.recurrence?`Occurrence completed · next due ${r.task.dueDate}`:name==='archive_task'?'Moved to Trash':name==='restore_task'?'Task restored':'Task completed')}catch(e){setEditError((e as Error).message);toast.error((e as Error).message)}finally{setBusy(false)}}
async function move(t:Task,status:string){if(t.status===status)return;setBusy(true);try{await mutation('update_task',{id:t.id,expectedRevision:t.revision,patch:{status}});await refresh();toast.success(`Moved to ${labels[status]}`)}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
function download(data:any,name:string){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function completeBackup(version:2|3=2){setBusy(true);setRecoveryError('');try{if(version===3&&canWrite)throw new Error('Freeze board writes before downloading a migration backup.');const pages=[];let cursor:string|null=null;do{const page=await api(version===3?'export_migration_page':'export_backup_page',{cursor,pageSize:30});pages.push(page);cursor=page.nextCursor;}while(cursor);if(pages[0]?.version!==version)throw new Error('The server returned an unsupported backup version.');await validateBackup(pages);download({format:version===3?'task-board-local-backup':'task-board-complete-backup',version,pages},`task-board-${version===3?'migration':'complete'}-${new Date().toISOString().replaceAll(':','-')}.json`);toast.success(version===3?'Migration backup verified and downloaded':'Complete backup verified and downloaded')}catch(e){setRecoveryError((e as Error).message);toast.error('Backup incomplete. No complete file was downloaded.')}finally{setBusy(false)}}
async function exportAll(){try{download(await api('export_tasks'),`task-board-${new Date().toISOString().slice(0,10)}.json`)}catch(e){toast.error((e as Error).message)}}
async function openRecovery(){setRecovery(true);setRecoveryError('');setImportData(null);setPreview(null);try{setSnapshots((await api('list_snapshots')).snapshots)}catch(e){setRecoveryError((e as Error).message)}}
async function previewData(data:any){setImportData(null);setPreview(null);setRecoveryError('');try{const p=await api('preview_import',{data});setImportData(data);setPreview(p)}catch(e){setRecoveryError((e as Error).message)}}
async function fileChanged(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;try{if(f.size>1500000)throw new Error('Choose an export under 1.5 MB');await previewData(JSON.parse(await f.text()))}catch(err){setRecoveryError((err as Error).message)}e.target.value=''}
async function importCopies(){setBusy(true);setRecoveryError('');try{const args={data:importData,digest:preview.digest};const result=await api('import_tasks',{...args,requestKey:requestKey('import_tasks',args)});await refresh();setPreview(null);setImportData(null);setSnapshots((await api('list_snapshots')).snapshots);toast.success(`${result.createdIds.length} tasks imported as copies`)}catch(e){setRecoveryError((e as Error).message)}finally{setBusy(false)}}
const active=tasks.filter(t=>['ToDo','InProgress','OnHold'].includes(t.status));
const columns=view==='active'?['ToDo','InProgress','OnHold']:view==='closed'?['Completed','Canceled']:view==='reference'?['Reference']:[];
const visible=view==='trash'?archived:tasks;
return <main className="app"><Toaster position="bottom-center" richColors/>
<header className="topbar"><div className="brand"><div className="brandmark"><Columns3 size={20}/></div><div><h1>Yet Another Task Board</h1><p><ShieldCheck size={12}/> Private board <span className="divider">/</span> Saved task records</p></div></div><div className="topactions">{canManageAccess===true&&<button className="quiet" onClick={openAccess}><ShieldCheck size={16}/><span>Access</span></button>}<button className="quiet" aria-label="Export task data" title="Export task data" onClick={openRecovery}><ArrowDownToLine size={16}/><span>Export</span></button><button className="quiet" aria-label="Open recovery and import tools" title="Recovery and import" onClick={openRecovery}><RotateCcw size={16}/><span>Recovery</span></button><button className="primary" disabled={!canWrite} onClick={create}><Plus size={17}/> New task</button><form action="/auth/signout" method="post" onSubmit={e=>{if(detailRef.current&&!detailRef.current.canLeave())e.preventDefault()}}><button className="quiet" type="submit">Sign out</button></form></div></header>
{!canWrite&&<section className="sample-note" role="status"><p>This board is read-only. You can view and export saved records.</p></section>}
{tasks.some(t=>t.sample)&&<section className="sample-note"><span className="sample-tag">SAMPLE DATA</span><p>Fictional sample tasks are included in this view. <span>No automatic chat sync or reminders.</span></p></section>}
<section className="workspace">
<div className="workspace-heading"><div><h2>Next actions, in view</h2><p>{active.length} active · {active.filter(t=>t.attention!=='none').length} need attention</p></div><button className="icon-button" aria-label="Refresh tasks" onClick={()=>refresh().catch(e=>setError(e.message))}><RefreshCw size={17}/></button></div>
<Tabs value={view} onValueChange={setView}><TabsList className="view-tabs"><TabsTrigger value="active">Active <span>{active.length}</span></TabsTrigger><TabsTrigger value="closed">Closed <span>{tasks.filter(t=>['Completed','Canceled'].includes(t.status)).length}</span></TabsTrigger><TabsTrigger value="reference">Reference</TabsTrigger><TabsTrigger value="trash">Trash <span>{archived.length}</span></TabsTrigger></TabsList>
{error&&<div className="error" role="alert">{error}<button onClick={()=>{setLoading(true);refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false))}}>Retry</button></div>}
{loading?<div className="load" role="status">Loading saved tasks…</div>:<TabsContent value={view}>
{view==='trash'?<div className="trash-list">{archived.length===0?<div className="empty">Trash is empty. Archived tasks can be restored here.</div>:archived.map(t=><button key={t.id} className="trash-row" onClick={()=>edit(t)}><Archive size={17}/><strong>{t.title}</strong><span>{labels[t.status]}</span><ArrowUpRight size={16}/></button>)}</div>:<div className={`board columns-${columns.length}`}>{columns.map(status=><section key={status} className={`column ${status}`} onDragOver={e=>{if(canWrite&&view==='active')e.preventDefault()}} onDrop={e=>{e.preventDefault();const t=tasks.find(x=>x.id===e.dataTransfer.getData('text/plain'));if(canWrite&&t&&view==='active')void move(t,status)}}><div className="column-heading"><div><span className="status-dot"/><h3>{labels[status]}</h3></div><span>{visible.filter(t=>t.status===status).length}</span></div><div className="cards">{visible.filter(t=>t.status===status).map(t=><button className="task-card" key={t.id} draggable={canWrite&&!busy&&view==='active'} onDragStart={e=>e.dataTransfer.setData('text/plain',t.id)} onClick={()=>edit(t)}><div className="card-top"><span>{t.category||'General'}</span>{t.sample&&<span className="sample-mini">SAMPLE</span>}</div><h4>{t.title.replace(/^SAMPLE · /,'')}</h4>{t.nextAction&&<p className="next-action">{t.nextAction}</p>}{t.attention!=='none'&&<div className={`attention ${t.attention}`}><span/>{t.attention==='review'?'Needs review':t.attention==='blocked'?'Blocked':'Waiting'}{t.blocker&&<p>{t.blocker}</p>}</div>}<div className="card-footer">{t.dueDate?<span><Clock3 size={13}/>{t.dueDate.slice(5).replace('-',' / ')}{t.recurrence&&<Repeat2 size={12}/>}</span>:<span>No due date</span>}<span>{t.sourceVerifiedAt?'Source checked':'Source unverified'}</span></div></button>)}{visible.filter(t=>t.status===status).length===0&&<div className="empty-column">{status==='ToDo'?'A clear place for the next step.':'Nothing here yet.'}</div>}</div></section>)}</div>}
</TabsContent>}
</Tabs><footer className="workspace-footer"><span>Changes save to your private database</span><span>Open a card to edit, complete, or move it</span></footer></section>
<AccessDialog open={accessOpen} canManageAccess={canManageAccess} canWrite={canWrite} onClose={()=>setAccessOpen(false)} returnFocus={returnFocus}/>
<TaskDetails ref={detailRef} canWrite={canWrite} open={open} taskId={selected?.id??null} onClose={()=>setOpen(false)} onChanged={refresh} returnFocus={returnFocus}/>
<Dialog open={recovery} onOpenChange={setRecovery}><DialogContent className="recovery-dialog sm:max-w-[560px]"><DialogHeader><DialogTitle>Export & recovery</DialogTitle><DialogDescription>Portable copies or a verified complete backup, including comments, images and history.</DialogDescription></DialogHeader><button className="secondary" onClick={exportAll}><ArrowDownToLine size={16}/> Portable task export</button><button className="primary" disabled={busy} onClick={()=>completeBackup(2)}>{busy?'Preparing and verifying…':'Download complete backup'}</button><p className="help">Complete backups include every task, comment revision, image and recovery snapshot. All pages and image checksums are verified before download. Recovery is supported into an empty isolated database using the supplied recovery script; this does not replace live data. Access settings are separate and are not included in task backups.</p><button className="secondary" disabled={busy||canWrite} onClick={()=>completeBackup(3)}>{busy?'Preparing and verifying…':'Download migration backup (v3)'}</button><p className="help">Migration backups preserve original image upload retry keys and the storage owner. Freeze writes first and drain accepted uploads. This download validates every page and image before saving; it does not import or replace live data.</p><input type="file" accept="application/json,.json" ref={fileRef} onChange={fileChanged} hidden/><button className="secondary" onClick={()=>fileRef.current?.click()}>Choose JSON to preview</button><p className="help">Portable exports include task fields, comments and normalized images up to 750 KB total, 100 tasks and 2,000 history events. Larger boards need a complete backup. Import previews accept portable versions 1 and 2 only, create new copies, remap image/comment links, and preserve original history in a source snapshot.</p>
{recoveryError&&<p className="error" role="alert">{recoveryError}</p>}{preview&&<div className="import-preview"><h3>Ready to import {preview.summary.taskCount} tasks</h3><p>{preview.summary.sampleCount} samples · {preview.summary.archivedCount} archived · {preview.summary.historyCount} history events</p><p>{preview.summary.mode}</p><button className="primary" disabled={busy||!canWrite} onClick={importCopies}>{busy?'Importing…':'Import as new copies'}</button></div>}
<h3 className="section-label">Saved snapshots</h3>{snapshots.length===0?<p className="help">A snapshot is saved automatically before each import.</p>:<div className="snapshot-list">{snapshots.map(s=><div key={s.id}><span>{s.id.startsWith('before:')?'Before import':'Imported source'}<small>{new Date(s.created_at).toLocaleString()}</small></span><button className="quiet" onClick={async()=>{try{await previewData(await api('get_snapshot',{id:s.id}))}catch(e){setRecoveryError((e as Error).message)}}}>Preview</button><button className="icon-button" aria-label="Download snapshot" onClick={async()=>{try{download(await api('get_snapshot',{id:s.id}),'task-board-snapshot.json')}catch(e){setRecoveryError((e as Error).message)}}}><ArrowDownToLine size={16}/></button></div>)}</div>}
</DialogContent></Dialog></main>}
