'use client';
import {forwardRef,useEffect,useImperativeHandle,useRef,useState,type ReactNode} from 'react';
import {ArrowUpRight,Check,Edit3,ImagePlus,Link2,MapPin,MessageSquare,Package,Plus,RotateCcw,Trash2,X} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {labels,statuses,inputOf,validateTask,type Task,type TaskInput,type Comment,type Attachment} from '@/lib/model';
import {safeHttpUrl} from '@/lib/safety';
import {toast} from 'sonner';
const empty=()=>validateTask({title:'Untitled task'});
async function api(name:string,args:any={},signal?:AbortSignal){const r=await fetch('/api/board',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,args}),signal});const value:any=await r.json();if(!r.ok)throw new Error(value.message||'Could not save. Your draft is still here.');return value}
export function SafeText({text}:{text:string}){const parts:ReactNode[]=[];const pattern=/https?:\/\/[^\s<>"']+/gi;let start=0;for(const match of text.matchAll(pattern)){const at=match.index!;parts.push(text.slice(start,at));const raw=match[0].replace(/[.,;!?)\]}]+$/,'');const url=safeHttpUrl(raw);parts.push(url?<a key={at} href={url} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{raw}</a>:raw);parts.push(match[0].slice(raw.length));start=at+match[0].length}parts.push(text.slice(start));return <div className="read-text">{parts}</div>}
function External({url,children,className=''}:{url:string,children:ReactNode,className?:string}){const safe=safeHttpUrl(url);return safe?<a className={className} href={safe} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{children}<ArrowUpRight size={15} aria-hidden="true"/></a>:<span>{children}</span>}
function AutoText({label,value,onChange,required=false}:{label:string,value:string,onChange:(v:string)=>void,required?:boolean}){const ref=useRef<HTMLTextAreaElement>(null);useEffect(()=>{const e=ref.current;if(e){e.style.height='auto';e.style.height=e.scrollHeight+'px'}},[value]);return <label className="field"><span>{label}</span><textarea ref={ref} className="grow-text" value={value} onChange={e=>onChange(e.target.value)} required={required} rows={2}/></label>}
function Input({label,value,onChange,type='text',placeholder=''}:{label:string,value:string,onChange:(v:string)=>void,type?:string,placeholder?:string}){return <label className="field"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)} type={type} placeholder={placeholder}/></label>}
function Choice({label,value,options,onChange}:{label:string,value:string,options:[string,string][],onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem value={v} key={v}>{l}</SelectItem>)}</SelectContent></Select></label>}
function eventLabel(e:any){if(e.action==='create')return 'Task created';if(e.action==='archive')return 'Moved to Trash';if(e.action==='restore')return 'Restored from Trash';if(e.action==='complete')return e.after?.recurrence?`Occurrence completed · next ${e.after.dueDate}`:'Task completed';const names:Record<string,string>={title:'title',status:'status',category:'group',nextAction:'next action',attention:'attention',blocker:'blocker',dueDate:'due date',dueTime:'due time',timezone:'timezone',recurrence:'recurrence',sourceUrl:'source link',sourceChatId:'source chat',sourceVerifiedAt:'source verification',evidenceNote:'notes',resources:'links and places'};const changes=Object.keys(names).filter(k=>JSON.stringify(e.before?.[k])!==JSON.stringify(e.after?.[k])).map(k=>names[k]);return changes.length?'Updated '+changes.join(', '):'Task updated'}
async function prepareImage(file:File){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024)throw new Error('Choose a PNG, JPEG or WebP under 8 MB');const bitmap=await createImageBitmap(file);try{if(!bitmap.width||!bitmap.height||bitmap.width*bitmap.height>40_000_000)throw new Error('Image dimensions are too large');const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext('2d');if(!context)throw new Error('Image preparation is unavailable');context.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(v=>v?resolve(v):reject(new Error('Could not prepare image')),'image/png'));if(blob.size>2*1024*1024)throw new Error('This image is over 2 MB after normalization. Try a smaller crop');return blob}finally{bitmap.close()}}
export type TaskDetailsHandle={canLeave:()=>boolean};
export const TaskDetails=forwardRef<TaskDetailsHandle,{open:boolean,taskId:string|null,onClose:()=>void,onChanged:()=>Promise<void>,returnFocus:React.RefObject<HTMLElement|null>}>(({open,taskId,onClose,onChanged,returnFocus},ref)=>{
 const [task,setTask]=useState<Task|null>(null),[draft,setDraft]=useState<TaskInput>(empty),[editing,setEditing]=useState(false),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<any[]>([]);
 const [comments,setComments]=useState<Comment[]>([]),[attachments,setAttachments]=useState<Record<string,Attachment>>({}),[cursor,setCursor]=useState<string|null>(null),[commentText,setCommentText]=useState(''),[draftImages,setDraftImages]=useState<Attachment[]>([]),[commentEdit,setCommentEdit]=useState<Comment|null>(null),[commentError,setCommentError]=useState(''),[commentsRefreshNeeded,setCommentsRefreshNeeded]=useState(false),[commentBusy,setCommentBusy]=useState(false),[commentsLoading,setCommentsLoading]=useState(false),[uploading,setUploading]=useState(false),[viewer,setViewer]=useState<Attachment|null>(null);
 const requestEpoch=useRef(0),keys=useRef(new Map<string,string>()),fileInput=useRef<HTMLInputElement>(null),uploadAbort=useRef<AbortController|null>(null),loadAbort=useRef<AbortController|null>(null);
 const dirty=editing&&(task?JSON.stringify(draft)!==JSON.stringify(inputOf(task)):draft.title!=='Untitled task'||JSON.stringify(draft)!==JSON.stringify(empty()));
 const commentDirty=!!commentText.trim()||draftImages.length>0||!!commentEdit;
 function canLeave(){if(!open)return true;if(busy||commentBusy)return false;return !(dirty||commentDirty||uploading)||window.confirm('Discard the unsaved draft? Saved task data will stay unchanged.')}
 useImperativeHandle(ref,()=>({canLeave}));
 function close(){if(!canLeave())return;requestEpoch.current++;loadAbort.current?.abort();uploadAbort.current?.abort();onClose()}
 function key(name:string,args:any){const fp=JSON.stringify({name,args});if(!keys.current.has(fp))keys.current.set(fp,crypto.randomUUID());return keys.current.get(fp)!}
 async function mutate(name:string,args:any){const result=await api(name,{...args,requestKey:key(name,args)});keys.current.delete(JSON.stringify({name,args}));return result}
 function mergeImages(values:Attachment[]){setAttachments(old=>({...old,...Object.fromEntries(values.map(a=>[a.id,a]))}))}
 async function loadComments(id:string,more:string|null=null,epoch=requestEpoch.current){setCommentsLoading(true);try{const result=await api('list_comments',{taskId:id,cursor:more},loadAbort.current?.signal);if(epoch!==requestEpoch.current)return;setComments(old=>more?[...new Map([...old,...result.comments].map(c=>[c.id,c])).values()]:result.comments);mergeImages(result.attachments);setCursor(result.nextCursor)}catch(e){if(epoch!==requestEpoch.current||loadAbort.current?.signal.aborted)return;throw e}finally{if(epoch===requestEpoch.current)setCommentsLoading(false)}}
 async function load(id:string){loadAbort.current?.abort();const controller=new AbortController();loadAbort.current=controller;const epoch=++requestEpoch.current;setLoading(true);setError('');setTask(null);setHistory([]);setComments([]);setAttachments({});setCursor(null);try{const [result,conversation]=await Promise.all([api('get_task',{id},controller.signal),api('list_comments',{taskId:id},controller.signal)]);if(epoch!==requestEpoch.current)return;setTask(result.task);setDraft(inputOf(result.task));setHistory(result.history);setComments(conversation.comments);mergeImages(conversation.attachments);setCursor(conversation.nextCursor)}catch(e){if(epoch===requestEpoch.current&&!controller.signal.aborted)setError((e as Error).message)}finally{if(epoch===requestEpoch.current)setLoading(false)}}
 useEffect(()=>{if(!open)return;setError('');setCommentError('');setCommentsRefreshNeeded(false);setUploading(false);setCommentsLoading(false);setCommentText('');setDraftImages([]);setCommentEdit(null);setEditing(!taskId);setViewer(null);if(taskId)void load(taskId);else{loadAbort.current?.abort();loadAbort.current=new AbortController();requestEpoch.current++;setTask(null);setDraft(empty());setHistory([]);setComments([]);setAttachments({});setCursor(null);setLoading(false)}return()=>{requestEpoch.current++;loadAbort.current?.abort();uploadAbort.current?.abort()}},[open,taskId]);
 useEffect(()=>{if(!open||(!dirty&&!commentDirty&&!uploading))return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[open,dirty,commentDirty,uploading]);
 function change(k:keyof TaskInput,value:any){setDraft(d=>({...d,[k]:value}))}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const args=task?{id:task.id,expectedRevision:task.revision,patch:draft}:{task:draft};const result=await mutate(task?'update_task':'create_task',args);setTask(result.task);setDraft(inputOf(result.task));setEditing(false);await onChanged();const latest=await api('get_task',{id:result.task.id});setHistory(latest.history);toast.success('Task saved')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function action(name:string){if(!task||dirty||commentDirty||uploading)return;setBusy(true);setError('');try{const result=await mutate(name,{id:task.id,expectedRevision:task.revision});setTask(result.task);setDraft(inputOf(result.task));await onChanged();const latest=await api('get_task',{id:task.id});setHistory(latest.history);toast.success(name==='complete_task'?'Saved completion':name==='restore_task'?'Task restored':'Moved to Trash')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(files:File[]){if(!task||uploading||commentBusy)return;if(draftImages.length+files.length>4){setCommentError('Attach up to four images to one comment');return}setUploading(true);setCommentError('');const controller=new AbortController();uploadAbort.current=controller;const epoch=requestEpoch.current;try{for(const file of files){const blob=await prepareImage(file);if(controller.signal.aborted)break;const requestKey=key('upload',{taskId:task.id,name:file.name,size:file.size,lastModified:file.lastModified});const r=await fetch('/api/images',{method:'POST',headers:{'Content-Type':'image/png','X-Task-Id':task.id,'X-Upload-Key':requestKey,'X-File-Name':encodeURIComponent(file.name)},body:blob,signal:controller.signal});const result:any=await r.json();if(!r.ok)throw new Error(result.message||'Image upload failed');if(epoch!==requestEpoch.current)return;setDraftImages(old=>old.some(a=>a.id===result.attachment.id)?old:[...old,result.attachment]);mergeImages([result.attachment])}}catch(e){if(!controller.signal.aborted&&epoch===requestEpoch.current)setCommentError((e as Error).message)}finally{if(epoch===requestEpoch.current)setUploading(false)}}
 function reconcileComment(comment:Comment){setComments(old=>[comment,...old.filter(c=>c.id!==comment.id)].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)))}
 async function refreshAfterComment(id:string,epoch:number){try{await loadComments(id,null,epoch)}catch{if(epoch===requestEpoch.current){setCommentsRefreshNeeded(true);setCommentError('Comment saved. The latest conversation could not refresh.')}}}
 async function post(){if(!task||commentBusy||uploading)return;const epoch=requestEpoch.current;setCommentBusy(true);setCommentError('');setCommentsRefreshNeeded(false);try{const args=commentEdit?{id:commentEdit.id,expectedRevision:commentEdit.revision,body:commentText,attachmentIds:draftImages.map(a=>a.id)}:{taskId:task.id,body:commentText,attachmentIds:draftImages.map(a=>a.id)};const result=await mutate(commentEdit?'edit_comment':'add_comment',args);if(epoch!==requestEpoch.current)return;reconcileComment(result.comment);setCommentText('');setDraftImages([]);setCommentEdit(null);toast.success(commentEdit?'Comment updated':'Comment posted');await refreshAfterComment(task.id,epoch)}catch(e){if(epoch===requestEpoch.current)setCommentError((e as Error).message)}finally{if(epoch===requestEpoch.current)setCommentBusy(false)}}
 async function commentAction(c:Comment){if(commentDirty||commentBusy)return;const epoch=requestEpoch.current;setCommentBusy(true);setCommentError('');setCommentsRefreshNeeded(false);try{const result=await mutate(c.archived?'restore_comment':'archive_comment',{id:c.id,expectedRevision:c.revision});if(epoch!==requestEpoch.current)return;reconcileComment(result.comment);await refreshAfterComment(c.taskId,epoch)}catch(e){if(epoch===requestEpoch.current)setCommentError((e as Error).message)}finally{if(epoch===requestEpoch.current)setCommentBusy(false)}}
 function editComment(c:Comment){if(commentDirty&&!window.confirm('Discard the current comment draft?'))return;setCommentText(c.body);setDraftImages(c.attachmentIds.map(id=>attachments[id]).filter(Boolean));setCommentEdit(c);setCommentError('');document.getElementById('task-comment-composer')?.scrollIntoView({behavior:'auto',block:'center'})}
 function cancelEdit(){if(dirty&&!window.confirm('Discard these unsaved task edits?'))return;if(task){setDraft(inputOf(task));setEditing(false);setError('')}else close()}
 function addResource(kind:'link'|'product'|'location'){change('resources',[...draft.resources,{kind,label:'',url:'',address:''}])}
 const links=task?[...new Set([task.sourceUrl,...(task.evidenceNote+'\n'+task.nextAction+'\n'+task.blocker).match(/https?:\/\/[^\s<>"']+/gi)||[]].map(s=>s.replace(/[.,;!?)\]}]+$/,'')).filter(s=>!!safeHttpUrl(s)))].slice(0,20):[];
 return <><Dialog open={open} onOpenChange={v=>{if(!v)close()}}><DialogContent className="task-detail-modal" onCloseAutoFocus={e=>{e.preventDefault();returnFocus.current?.focus()}} onInteractOutside={e=>{if(dirty||commentDirty||uploading)e.preventDefault()}}>
 <DialogHeader className="detail-header"><div className="detail-eyebrow">{editing?'EDIT TASK':'TASK DETAILS'}{dirty&&<span role="status">Unsaved changes</span>}</div><DialogTitle>{loading?'Loading task…':task?.title||'New task'}</DialogTitle><DialogDescription>{task?`${labels[task.status]} · ${task.category||'General'} · Revision ${task.revision}`:'A clear next action, with room for the details'}</DialogDescription></DialogHeader>
 {loading?<p className="load" role="status">Loading saved details and comments…</p>:<>
 {error&&<div className="error" role="alert">{error}{!task&&taskId&&<button onClick={()=>load(taskId)}>Retry loading task</button>}{task&&editing&&<button type="button" onClick={async()=>{try{const fresh=await api('get_task',{id:task.id});setTask(fresh.task);setHistory(fresh.history);setError('Saved revision reloaded. Your draft remains below; review it and save again.')}catch(e){setError((e as Error).message)}}}>Load current revision, keep my draft</button>}</div>}
 {editing?<form className="detail-editor" onSubmit={save}><fieldset disabled={busy} className="editor-fields">
 <AutoText label="Title" value={draft.title} onChange={v=>change('title',v)} required/>
 <div className="form-grid"><Input label="Group / category" value={draft.category} onChange={v=>change('category',v)}/><Choice label="Status" value={draft.status} options={statuses.filter(s=>s!=='Completed'||task?.status==='Completed').map(s=>[s,labels[s]])} onChange={v=>change('status',v)}/></div>
 <AutoText label="Next action" value={draft.nextAction} onChange={v=>change('nextAction',v)}/><div className="form-grid"><Choice label="Attention" value={draft.attention} options={[[ 'none','None'],['blocked','Blocked'],['waiting','Waiting for someone'],['review','Needs review']]} onChange={v=>change('attention',v)}/><Input label="Due date" type="date" value={draft.dueDate||''} onChange={v=>change('dueDate',v||null)}/></div><AutoText label="Blocker / awaiting" value={draft.blocker} onChange={v=>change('blocker',v)}/>
 <div className="form-grid"><Input label="Local due time" type="time" value={draft.dueTime||''} onChange={v=>change('dueTime',v||null)}/><Input label="Timezone" value={draft.timezone||''} onChange={v=>change('timezone',v||null)} placeholder="e.g. America/Toronto"/></div>
 <Choice label="Repeat" value={draft.recurrence?'monthly':'none'} options={[[ 'none','Does not repeat'],['monthly','Monthly']]} onChange={v=>change('recurrence',v==='monthly'?{frequency:'monthly',interval:1,anchorDay:draft.dueDate?Number(draft.dueDate.slice(-2)):1}:null)}/>
 {draft.recurrence&&<div className="form-grid"><Input label="Every (months)" type="number" value={String(draft.recurrence.interval)} onChange={v=>change('recurrence',{...draft.recurrence,interval:Number(v)})}/><Input label="Day of month" type="number" value={String(draft.recurrence.anchorDay)} onChange={v=>change('recurrence',{...draft.recurrence,anchorDay:Number(v)})}/></div>}
 <h3 className="section-label">Links & places</h3><Input label="Source URL" type="url" value={draft.sourceUrl} onChange={v=>{change('sourceUrl',v);if(v!==task?.sourceUrl)change('sourceVerifiedAt',null)}}/><Input label="Source chat ID" value={draft.sourceChatId} onChange={v=>change('sourceChatId',v)}/>
 {draft.resources.map((resource,i)=><div className="resource-editor" key={i}><div className="resource-editor-heading"><strong>{resource.kind==='product'?'Product':resource.kind==='location'?'Place':'Link'} {i+1}</strong><button className="icon-button" type="button" aria-label={`Remove ${resource.kind} ${i+1}`} onClick={()=>change('resources',draft.resources.filter((_,n)=>n!==i))}><X size={17}/></button></div><Input label="Label" value={resource.label} onChange={v=>change('resources',draft.resources.map((r,n)=>n===i?{...r,label:v}:r))}/>{resource.kind==='location'&&<Input label="Address or place" value={resource.address} onChange={v=>change('resources',draft.resources.map((r,n)=>n===i?{...r,address:v}:r))}/>}<Input label={resource.kind==='location'?'Website or map URL (optional)':'URL'} type="url" value={resource.url} onChange={v=>change('resources',draft.resources.map((r,n)=>n===i?{...r,url:v}:r))}/></div>)}
 {draft.resources.length<12&&<div className="detail-actions"><button type="button" className="secondary" onClick={()=>addResource('product')}><Package size={16}/> Add product</button><button type="button" className="secondary" onClick={()=>addResource('location')}><MapPin size={16}/> Add place</button><button type="button" className="quiet" onClick={()=>addResource('link')}><Link2 size={16}/> Add link</button></div>}
 <AutoText label="Notes & evidence" value={draft.evidenceNote} onChange={v=>change('evidenceNote',v)}/>
 <div className="detail-actions editor-actions"><button className="primary" disabled={busy} type="submit">{busy?'Saving…':'Save changes'}</button><button className="secondary" type="button" disabled={busy} onClick={cancelEdit}>Cancel editing</button>{dirty&&<span className="help">Draft not saved yet</span>}</div></fieldset></form>:task&&<>
 <div className="detail-actions"><button className="primary" disabled={busy||task.archived} onClick={()=>setEditing(true)}><Edit3 size={16}/> Edit task</button>{task.archived?<button className="secondary" disabled={busy||commentDirty} onClick={()=>action('restore_task')}><RotateCcw size={16}/> Restore task</button>:<><button className="secondary" disabled={busy||commentDirty||uploading||task.status==='Completed'} onClick={()=>action('complete_task')}><Check size={16}/>{task.recurrence?'Complete occurrence':'Complete'}</button><button className="quiet" disabled={busy||commentDirty||uploading} onClick={()=>action('archive_task')}><Trash2 size={16}/> Move to Trash</button></>}</div>
 {task.archived&&<p className="sample-detail">This task is in recoverable Trash. Its notes, comments and images are preserved.</p>}
 <div className="detail-columns"><section className="detail-main">
 <section className="read-section"><h3>Next action</h3>{task.nextAction?<SafeText text={task.nextAction}/>:<p className="empty-detail">No next action recorded</p>}</section>
 {(task.blocker||task.attention!=='none')&&<section className="read-section attention-section"><h3>{task.attention==='review'?'Needs your review':task.attention==='waiting'?'Waiting for':task.attention==='blocked'?'Blocked':'Blocker / awaiting'}</h3>{task.blocker?<SafeText text={task.blocker}/>:<p className="empty-detail">No additional details</p>}</section>}
 <section className="read-section"><h3>Notes & evidence</h3>{task.evidenceNote?<SafeText text={task.evidenceNote}/>:<p className="empty-detail">No notes yet. Add a comment below or edit the task.</p>}</section>
 </section><aside className="detail-context"><section className="context-card"><h3>Schedule</h3><p>{task.dueDate||'No due date'}{task.dueTime&&` · ${task.dueTime}`}</p>{task.timezone&&<small>{task.timezone}</small>}{task.recurrence&&<p className="help">Every {task.recurrence.interval===1?'month':`${task.recurrence.interval} months`} on day {task.recurrence.anchorDay}. Completing advances one occurrence; shorter months use their last day.</p>}</section>
 {task.resources.map((r,i)=><section className="context-card resource-card" key={i}><h3>{r.kind==='product'?<Package size={15}/>:r.kind==='location'?<MapPin size={15}/>:<Link2 size={15}/>} {r.kind==='product'?'Product':r.kind==='location'?'Place':'Link'}</h3><strong>{r.label}</strong>{r.address&&<p>{r.address}</p>}{r.url&&<External url={r.url} className="resource-action">{r.kind==='product'?'View product':'Open link'}</External>}{r.kind==='location'&&r.address&&<External url={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(r.address)}`} className="resource-action">View on map</External>}</section>)}
 {links.length>0&&<section className="context-card"><h3><Link2 size={15}/> Task links</h3>{links.map(url=><External key={url} url={url} className="source-link"><span>{new URL(url).hostname}<small>{url}</small></span></External>)}</section>}
 <section className="context-card"><h3>Source check</h3><p>{task.sourceVerifiedAt?new Date(task.sourceVerifiedAt).toLocaleString():'Not verified'}</p><small>Links open only when you click. No automatic preview or location request.</small>{task.sourceChatId&&<details><summary>Source chat ID</summary><code>{task.sourceChatId}</code></details>}</section>
 </aside></div>
 <section className="comments-section"><div className="section-heading"><h3><MessageSquare size={17}/> Comments</h3><span>{comments.length}{cursor?'+':''}</span></div>
 {comments.length===0&&<p className="empty-detail">Add an update, a useful link, or an image.</p>}
 <div className="comment-list">{comments.map(c=><article className={`comment ${c.archived?'comment-removed':''}`} key={c.id}><header><span>{new Date(c.createdAt).toLocaleString()}{c.revision>1&&!c.archived&&' · edited'}</span><div>{!task.archived&&<>{!c.archived&&<button className="quiet" disabled={commentBusy} onClick={()=>editComment(c)}>Edit</button>}<button className="quiet" disabled={commentBusy||commentDirty} onClick={()=>commentAction(c)}>{c.archived?'Restore':'Remove'}</button></>}</div></header>{c.archived?<p className="empty-detail">Comment removed. It can be restored.</p>:<><SafeText text={c.body}/><div className="image-grid">{c.attachmentIds.map(id=>attachments[id]&&<button key={id} className="image-thumb" onClick={()=>setViewer(attachments[id])}><img src={`/api/images?id=${encodeURIComponent(id)}`} alt={attachments[id].filename} loading="lazy"/><span>{attachments[id].filename}</span></button>)}</div></>}</article>)}</div>
 {cursor&&<button className="secondary" disabled={commentsLoading} onClick={()=>loadComments(task.id,cursor).catch(e=>setCommentError(e.message))}>Load older comments</button>}
 {!task.archived&&<div id="task-comment-composer" className="comment-composer" onDragOver={e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault()}} onDrop={e=>{e.preventDefault();void upload([...e.dataTransfer.files])}} onPaste={e=>{const files=[...e.clipboardData.files].filter(f=>f.type.startsWith('image/'));if(files.length){e.preventDefault();void upload(files)}}}><fieldset disabled={commentBusy} className="comment-fields"><AutoText label={commentEdit?'Edit comment':'Add a comment'} value={commentText} onChange={setCommentText}/><div className="draft-images">{draftImages.map(a=><div key={a.id}><img src={`/api/images?id=${a.id}`} alt={a.filename}/><span>{a.filename}</span><button className="icon-button" aria-label={`Remove ${a.filename} from draft`} onClick={()=>setDraftImages(old=>old.filter(x=>x.id!==a.id))}><X size={16}/></button></div>)}</div><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp" multiple hidden onChange={e=>{void upload([...e.target.files||[]]);e.target.value=''}}/>
 <div className="detail-actions"><button className="primary" disabled={commentBusy||uploading||(!commentText.trim()&&!draftImages.length)} onClick={post}>{commentBusy?'Saving…':commentEdit?'Save comment':'Post comment'}</button><button className="secondary" disabled={uploading||draftImages.length>=4||commentBusy} onClick={()=>fileInput.current?.click()}><ImagePlus size={16}/> Add images</button>{uploading&&<button className="quiet" onClick={()=>uploadAbort.current?.abort()}>Cancel upload</button>}{commentEdit&&<button className="quiet" onClick={()=>{if(window.confirm('Discard this comment edit?')){setCommentEdit(null);setCommentText('');setDraftImages([])}}}>Cancel edit</button>}</div>
 {uploading&&<p className="help" role="status">Preparing and uploading image…</p>}<p className="help">Paste or drop PNG, JPEG or WebP images. Up to 4 per comment. Images are resized to 1600px, normalized to PNG and stripped of metadata; originals are not retained. Maximum 2 MB each. Removed draft uploads stay private and are included in backups.</p></fieldset></div>}
 {commentError&&<div className="error" role="alert">{commentError}{commentsRefreshNeeded&&<button disabled={commentsLoading} onClick={async()=>{try{await loadComments(task.id);setCommentsRefreshNeeded(false);setCommentError('')}catch{setCommentError('Comment saved. The latest conversation could not refresh.')}}}>Refresh comments</button>}{commentEdit&&<button onClick={async()=>{try{const fresh=await api('get_comment',{id:commentEdit.id});setCommentEdit(fresh.comment);mergeImages(fresh.attachments);setCommentError('Current comment revision loaded. Your draft is preserved; review it and save again.')}catch(e){setCommentError((e as Error).message)}}}>Load current comment revision, keep my draft</button>}</div>}
 </section><details className="activity-section"><summary>Task activity · latest {history.length}</summary>{history.map((e,i)=><div key={i}><strong>{eventLabel(e)}</strong><span>{new Date(e.createdAt).toLocaleString()}</span></div>)}<p className="help">Complete backups include the full task and comment history.</p></details><p className="task-id">Task ID: {task.id}</p>
 </>}
 </>}
 </DialogContent></Dialog><Dialog open={!!viewer} onOpenChange={v=>{if(!v)setViewer(null)}}><DialogContent className="image-viewer"><DialogHeader><DialogTitle>{viewer?.filename||'Image'}</DialogTitle><DialogDescription>Private task image</DialogDescription></DialogHeader>{viewer&&<img src={`/api/images?id=${viewer.id}`} alt={viewer.filename}/>}</DialogContent></Dialog></>
});
TaskDetails.displayName='TaskDetails';
