import {z} from 'zod';
import {AppError} from './errors';
import {commentSchema,attachmentSchema,type Task,type Comment,type Attachment} from './model';
import {stable,hash,stableId} from './safety';
import {normalizePng} from './image';
const keySchema=z.string().min(8).max(120).regex(/^[A-Za-z0-9_.:-]+$/),idSchema=z.string().uuid();
export const commentInput=z.object({body:z.string().trim().max(5000),attachmentIds:z.array(idSchema).max(4).default([])}).strict().refine(v=>v.body.length>0||v.attachmentIds.length>0,'Write a comment or attach an image');
export class ActivityService {
 constructor(private db:D1Database,private owner:string,private images:R2Bucket|undefined,private task:(id:string)=>Promise<Task>){if(!owner)throw new AppError(401,'sign_in_required','Sign in first')}
 async list(taskId:string,cursor:string|null=null){await this.task(taskId);let after=Number.MAX_SAFE_INTEGER;if(cursor){try{const c=JSON.parse(atob(cursor));if(c.taskId!==taskId||c.owner!==await hash(this.owner))throw 0;after=z.number().int().nonnegative().parse(c.after)}catch{throw new AppError(400,'invalid_cursor','Invalid comment cursor')}}const rows=await this.db.prepare('SELECT rowid AS position,payload FROM comments WHERE owner=? AND task_id=? AND rowid<? ORDER BY rowid DESC LIMIT 31').bind(this.owner,taskId,after).all<any>();const comments=rows.results.slice(0,30).map(r=>commentSchema.parse(JSON.parse(r.payload)));const ids=[...new Set(comments.flatMap(c=>c.attachmentIds))];const attachments=[];for(const id of ids)attachments.push(await this.metadata(id,taskId));return {comments,attachments,nextCursor:rows.results.length>30?btoa(JSON.stringify({taskId,owner:await hash(this.owner),after:rows.results[29].position})):null}}
 async get(id:string){const row=await this.db.prepare('SELECT payload FROM comments WHERE owner=? AND id=?').bind(this.owner,idSchema.parse(id)).first<{payload:string}>();if(!row)throw new AppError(404,'not_found','Comment not found');return commentSchema.parse(JSON.parse(row.payload))}
 async replay(key:string,fp:string){const row=await this.db.prepare('SELECT fingerprint,after_json FROM comment_events WHERE owner=? AND request_key=?').bind(this.owner,key).first<any>();if(!row)return null;if(row.fingerprint!==fp)throw new AppError(409,'idempotency_conflict','This request key already belongs to different input');return commentSchema.parse(JSON.parse(row.after_json))}
 async mutate(action:'add'|'edit'|'archive'|'restore',args:any){const key=keySchema.parse(args.requestKey),fp=await hash(stable({action,...args}));const previous=await this.replay(key,fp);if(previous)return previous;let before:Comment|null=null;if(action!=='add')before=await this.get(args.id);const taskId=before?.taskId??idSchema.parse(args.taskId);const task=await this.task(taskId);if(task.archived)throw new AppError(400,'archived_task','Restore this task before changing comments');if(before&&before.revision!==args.expectedRevision)throw new AppError(409,'revision_conflict','This comment changed. Your draft is still here; reload the saved comment before trying again');
 let content=action==='add'||action==='edit'?commentInput.parse({body:args.body,attachmentIds:args.attachmentIds??before?.attachmentIds??[]}):before!;
 if(new Set(content.attachmentIds).size!==content.attachmentIds.length)throw new AppError(400,'invalid_input','Duplicate attachments');for(const id of content.attachmentIds)await this.metadata(id,taskId);
 const now=new Date().toISOString();const next:Comment=before?{...before,body:content.body,attachmentIds:content.attachmentIds,revision:before.revision+1,updatedAt:now,archived:action==='archive'?true:action==='restore'?false:before.archived}:{id:crypto.randomUUID(),taskId,body:content.body,attachmentIds:content.attachmentIds,revision:1,createdAt:now,updatedAt:now,archived:false};
 if(action==='edit'&&before?.archived)throw new AppError(400,'archived_comment','Restore this comment before editing');
 const body=JSON.stringify(next);const write=before?this.db.prepare('UPDATE comments SET payload=?,revision=?,last_mutation=? WHERE owner=? AND id=? AND revision=? AND NOT EXISTS(SELECT 1 FROM comment_events WHERE owner=? AND request_key=?)').bind(body,next.revision,key,this.owner,next.id,before.revision,this.owner,key):this.db.prepare('INSERT INTO comments(owner,id,task_id,payload,revision,last_mutation) SELECT ?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM comment_events WHERE owner=? AND request_key=?) AND (SELECT COUNT(*) FROM comments WHERE owner=?)<500').bind(this.owner,next.id,taskId,body,1,key,this.owner,key,this.owner);
 await this.db.batch([write,this.db.prepare('INSERT INTO comment_events(owner,request_key,fingerprint,comment_id,task_id,action,before_json,after_json,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM comments WHERE owner=? AND id=? AND last_mutation=?) ON CONFLICT(owner,request_key) DO NOTHING').bind(this.owner,key,fp,next.id,taskId,action,before?JSON.stringify(before):null,body,now,this.owner,next.id,key)]);const result=await this.replay(key,fp);if(!result)throw new AppError(409,'revision_conflict','Comment changed or the 500-comment board limit was reached. Your draft was not applied');return result}
 async metadata(id:string,taskId?:string){const row=await this.db.prepare('SELECT payload,ready FROM attachments WHERE owner=? AND id=?').bind(this.owner,idSchema.parse(id)).first<any>();if(!row||!row.ready)throw new AppError(404,'not_found','Image not found or upload is incomplete');const a=attachmentSchema.parse(JSON.parse(row.payload));if(taskId&&a.taskId!==taskId)throw new AppError(404,'not_found','Image not found');await this.task(a.taskId);return a}
 async image(id:string){const a=await this.metadata(id);const row=await this.db.prepare('SELECT object_key FROM attachments WHERE owner=? AND id=?').bind(this.owner,id).first<any>();if(!this.images)throw new AppError(503,'storage_unavailable','Image storage is unavailable');const object=await this.images.get(row.object_key);if(!object)throw new AppError(503,'image_unavailable','The image is unavailable; metadata was preserved');return {metadata:a,object}}
 async upload(taskId:string,requestKey:string,bytes:Uint8Array,filename:string){const task=await this.task(idSchema.parse(taskId));keySchema.parse(requestKey);if(!this.images)throw new AppError(503,'storage_unavailable','Image storage is unavailable');const normalized=await normalizePng(bytes);const digest=await hash(normalized.bytes);const safeName=filename.replace(/[\x00-\x1f\x7f/\\]/g,'_').slice(0,155).replace(/\.[^.]+$/,'')+'.png';const fp=await hash(stable({taskId,digest,filename:safeName}));const id=await stableId(`${this.owner}:upload:${requestKey}`),objectKey=`images/${await hash(this.owner)}/${id}`;const a:Attachment={id,taskId,filename:safeName||'image.png',contentType:'image/png',size:normalized.bytes.length,width:normalized.width,height:normalized.height,sha256:digest,createdAt:new Date().toISOString()};
 const existing=await this.db.prepare('SELECT payload,fingerprint,ready FROM attachments WHERE owner=? AND id=?').bind(this.owner,id).first<any>();if(existing){if(existing.fingerprint!==fp)throw new AppError(409,'idempotency_conflict','Upload key already used for a different image');if(existing.ready)return attachmentSchema.parse(JSON.parse(existing.payload))}if(task.archived)throw new AppError(400,'archived_task','Restore this task before uploading images');
 await this.db.batch([this.db.prepare('INSERT INTO attachments(owner,id,task_id,payload,object_key,request_key,fingerprint,ready,size) SELECT ?,?,?,?,?,?,?,0,? WHERE (SELECT COUNT(*) FROM attachments WHERE owner=?)<100 AND (SELECT COALESCE(SUM(size),0) FROM attachments WHERE owner=?)+?<=104857600 ON CONFLICT(owner,id) DO NOTHING').bind(this.owner,id,taskId,JSON.stringify(a),objectKey,requestKey,fp,a.size,this.owner,this.owner,a.size)]);
 const row=await this.db.prepare('SELECT payload,fingerprint,ready FROM attachments WHERE owner=? AND id=?').bind(this.owner,id).first<any>();if(!row)throw new AppError(400,'image_quota','Board image limit reached: 100 images or 100 MB, including retained drafts');if(row.fingerprint!==fp)throw new AppError(409,'idempotency_conflict','Upload key already used for a different image');if(!row.ready){await this.images.put(objectKey,normalized.bytes,{onlyIf:{etagDoesNotMatch:'*'},httpMetadata:{contentType:'image/png'}});await this.db.batch([this.db.prepare('UPDATE attachments SET ready=1 WHERE owner=? AND id=? AND fingerprint=?').bind(this.owner,id,fp)])}return attachmentSchema.parse(JSON.parse(row.payload))}
 async all(){const rows=await this.db.batch([this.db.prepare('SELECT payload FROM comments WHERE owner=? ORDER BY rowid').bind(this.owner),this.db.prepare('SELECT comment_id,task_id,action,before_json,after_json,created_at FROM comment_events WHERE owner=? ORDER BY sequence LIMIT 2001').bind(this.owner),this.db.prepare('SELECT payload FROM attachments WHERE owner=? AND ready=1 ORDER BY rowid').bind(this.owner)]);if(rows[1].results.length>2000)throw new AppError(400,'portable_limit','Comment history exceeds the portable export limit. Download a complete backup');return {comments:rows[0].results.map((r:any)=>commentSchema.parse(JSON.parse(r.payload))),commentHistory:rows[1].results.map((r:any)=>({commentId:r.comment_id,taskId:r.task_id,action:r.action,before:r.before_json?JSON.parse(r.before_json):null,after:JSON.parse(r.after_json),createdAt:r.created_at})),attachments:rows[2].results.map((r:any)=>attachmentSchema.parse(JSON.parse(r.payload)))}}
}
