import {z} from 'zod';
import {AppError} from './errors';
import {taskSchema,commentSchema,attachmentSchema,exportSchema} from './model';
import {hash,stable,base64,unbase64,stableId} from './safety';
const uploadRetrySchema=z.object({attachmentId:z.string().uuid(),requestKey:z.string().min(8).max(120).regex(/^[A-Za-z0-9_.:-]+$/),fingerprint:z.string().regex(/^[a-f0-9]{64}$/)}).strict();
export async function backupPage(db:D1Database,owner:string,images:R2Bucket|undefined,cursor:string|null,pageSize:number){
 return capturePage(db,owner,images,cursor,pageSize,2)
}
/** Separate migration contract: keep original ready-upload retry state and storage ownership. */
export async function migrationPage(db:D1Database,owner:string,images:R2Bucket|undefined,cursor:string|null,pageSize:number){
 return capturePage(db,owner,images,cursor,pageSize,3)
}
async function capturePage(db:D1Database,owner:string,images:R2Bucket|undefined,cursor:string|null,pageSize:number,version:2|3){
 z.number().int().min(1).max(100).parse(pageSize);
 const ownerTag=await hash(owner);
 let keyRow=await db.prepare('SELECT secret FROM backup_keys WHERE owner=?').bind(owner).first<{secret:string}>();if(!keyRow){await db.batch([db.prepare('INSERT INTO backup_keys(owner,secret) VALUES(?,?) ON CONFLICT(owner) DO NOTHING').bind(owner,crypto.randomUUID()+crypto.randomUUID())]);keyRow=await db.prepare('SELECT secret FROM backup_keys WHERE owner=?').bind(owner).first<{secret:string}>()}
 const signingKey=await crypto.subtle.importKey('raw',new TextEncoder().encode(keyRow!.secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);
 const encode=async(c:any)=>base64(new TextEncoder().encode(JSON.stringify({payload:c,signature:base64(new Uint8Array(await crypto.subtle.sign('HMAC',signingKey,new TextEncoder().encode(stable(c)))))}))).replaceAll('+','-').replaceAll('/','_');let c:any;
 const finish=async(data:any,next:any)=>{const page={format:'task-board-backup-page',version, ...(version===3?{ownerTag}:{}),backupId:c.backupId,capturedAt:c.capturedAt,sequence:c.sequence,previousChecksum:c.previousChecksum,...data,complete:next===null};const checksum=await hash(stable(page));return {...page,checksum,nextCursor:next?await encode({...next,sequence:c.sequence+1,previousChecksum:checksum}):null}};
 if(!cursor){const r=await db.batch([
 db.prepare('SELECT payload FROM tasks WHERE owner=? ORDER BY id').bind(owner),
 db.prepare('SELECT COALESCE(MAX(rowid),0) AS high,COUNT(*) AS count FROM task_events WHERE owner=?').bind(owner),
 db.prepare('SELECT COALESCE(MAX(rowid),0) AS high,COUNT(*) AS count FROM snapshots WHERE owner=?').bind(owner),
 db.prepare('SELECT COALESCE(MAX(sequence),0) AS high,COUNT(*) AS count FROM comment_events WHERE owner=?').bind(owner),
 db.prepare('SELECT COUNT(*) AS count FROM comments WHERE owner=?').bind(owner),
 db.prepare(version===3?'SELECT id,task_id,payload,object_key,request_key,fingerprint,ready,size FROM attachments WHERE owner=? ORDER BY id':'SELECT payload FROM attachments WHERE owner=? AND ready=1 ORDER BY id').bind(owner)]);
 if(version===3&&r[5].results.some((row:any)=>row.ready!==1))throw new AppError(409,'migration_pending_uploads','Finish or review incomplete uploads before migration');
 const metadata=r[5].results.map((x:any)=>attachmentSchema.parse(JSON.parse(x.payload)));c={v:version,ownerTag,backupId:crypto.randomUUID(),capturedAt:new Date().toISOString(),historyHigh:Number((r[1].results[0] as any).high),snapshotHigh:Number((r[2].results[0] as any).high),commentHigh:Number((r[3].results[0] as any).high),phase:'history',after:0,attachments:metadata,attachmentIndex:0,attachmentOffset:0,sequence:0,previousChecksum:null};
 const uploadRetries=version===3?r[5].results.map((row:any)=>uploadRetrySchema.parse({attachmentId:row.id,requestKey:row.request_key,fingerprint:row.fingerprint})):undefined;
 if(version===3)for(let i=0;i<metadata.length;i++){const a=metadata[i],row:any=r[5].results[i];if(row.id!==a.id||a.id!==await stableId(`${owner}:upload:${uploadRetries![i].requestKey}`)||row.task_id!==a.taskId||row.size!==a.size||row.object_key!==`images/${ownerTag}/${a.id}`||uploadRetries![i].fingerprint!==await hash(stable({taskId:a.taskId,digest:a.sha256,filename:a.filename})))throw new AppError(409,'migration_retry_state','Authoritative upload retry state is unavailable or inconsistent')}
 if(version===3)c.uploadRetries=uploadRetries;
 return finish({pageKind:'manifest',...(version===3?{storageOwner:owner,uploadRetries}:{}),tasks:r[0].results.map((x:any)=>taskSchema.parse(JSON.parse(x.payload))),history:[],snapshots:[],commentHistory:[],attachments:metadata,attachmentParts:[],counts:{tasks:r[0].results.length,history:Number((r[1].results[0] as any).count),snapshots:Number((r[2].results[0] as any).count),comments:Number((r[4].results[0] as any).count),commentHistory:Number((r[3].results[0] as any).count),attachments:metadata.length,...(version===3?{uploadRetries:metadata.length}:{}),attachmentParts:metadata.reduce((n,a)=>n+Math.ceil(a.size/65536),0),attachmentBytes:metadata.reduce((n,a)=>n+a.size,0)}},c)
 }
 try{const envelope=JSON.parse(new TextDecoder().decode(unbase64(z.string().max(300000).parse(cursor).replaceAll('-','+').replaceAll('_','/'))));if(!await crypto.subtle.verify('HMAC',signingKey,unbase64(envelope.signature),new TextEncoder().encode(stable(envelope.payload))))throw 0;c=z.object({v:z.literal(version),ownerTag:z.string(),backupId:z.string().uuid(),capturedAt:z.string().datetime(),historyHigh:z.number().int().nonnegative(),snapshotHigh:z.number().int().nonnegative(),commentHigh:z.number().int().nonnegative(),phase:z.enum(['history','snapshots','commentHistory','images']),after:z.number().int().nonnegative(),attachments:z.array(attachmentSchema).max(100),attachmentIndex:z.number().int().nonnegative(),attachmentOffset:z.number().int().nonnegative(),sequence:z.number().int().positive(),previousChecksum:z.string().length(64),...(version===3?{uploadRetries:z.array(uploadRetrySchema).max(100)}:{})}).strict().parse(envelope.payload);if(c.ownerTag!==ownerTag)throw 0}catch{throw new AppError(400,'invalid_cursor','Invalid backup cursor for this owner')}
 if(version===3){const state=await db.batch([
  db.prepare('SELECT COALESCE(SUM(CASE WHEN ready=1 THEN 0 ELSE 1 END),0) AS pending,COUNT(*) AS count FROM attachments WHERE owner=?').bind(owner),
  db.prepare('SELECT COALESCE(MAX(rowid),0) AS high FROM task_events WHERE owner=?').bind(owner),
  db.prepare('SELECT COALESCE(MAX(rowid),0) AS high FROM snapshots WHERE owner=?').bind(owner),
  db.prepare('SELECT COALESCE(MAX(sequence),0) AS high FROM comment_events WHERE owner=?').bind(owner)]);
  const uploads=state[0].results[0] as any;if(Number(uploads.pending))throw new AppError(409,'migration_pending_uploads','Finish or review incomplete uploads before migration');
  if(Number(uploads.count)!==c.attachments.length||Number((state[1].results[0] as any).high)!==c.historyHigh||Number((state[2].results[0] as any).high)!==c.snapshotHigh||Number((state[3].results[0] as any).high)!==c.commentHigh)throw new AppError(409,'migration_source_changed','The source changed during migration capture; freeze it and start a new capture')
 }
 if(c.phase==='images'){const a=c.attachments[c.attachmentIndex];if(!a)return finish({pageKind:'images',tasks:[],history:[],snapshots:[],commentHistory:[],attachments:[],attachmentParts:[]},null);if(!images)throw new AppError(503,'storage_unavailable','Image storage is unavailable; this backup is incomplete');const row=await db.prepare(version===3?'SELECT object_key,payload,request_key,fingerprint FROM attachments WHERE owner=? AND id=? AND ready=1':'SELECT object_key,payload FROM attachments WHERE owner=? AND id=? AND ready=1').bind(owner,a.id).first<any>();if(!row||JSON.parse(row.payload).sha256!==a.sha256||(version===3&&(row.request_key!==c.uploadRetries[c.attachmentIndex]?.requestKey||row.fingerprint!==c.uploadRetries[c.attachmentIndex]?.fingerprint||row.object_key!==`images/${ownerTag}/${a.id}`||stable(JSON.parse(row.payload))!==stable(a))))throw new AppError(400,'invalid_cursor','Image capture metadata changed');const length=Math.min(65536,a.size-c.attachmentOffset);if(length<=0)throw new AppError(400,'invalid_cursor','Invalid image offset');const object=await images.get(row.object_key,{range:{offset:c.attachmentOffset,length}});if(!object)throw new AppError(503,'image_unavailable','A backup image is unavailable; do not treat this backup as complete');const bytes=new Uint8Array(await object.arrayBuffer());if(bytes.length!==length)throw new AppError(503,'image_unavailable','An image part is incomplete');let next={...c,attachmentOffset:c.attachmentOffset+bytes.length};if(next.attachmentOffset===a.size){next.attachmentIndex++;next.attachmentOffset=0}return finish({pageKind:'images',tasks:[],history:[],snapshots:[],commentHistory:[],attachments:[],attachmentParts:[{id:a.id,offset:c.attachmentOffset,dataBase64:base64(bytes),sha256:await hash(bytes)}]},next.attachmentIndex<c.attachments.length?next:null)}
 const sql=c.phase==='history'?'SELECT rowid AS position,request_key,fingerprint,task_id,action,before_json,after_json,created_at FROM task_events WHERE owner=? AND rowid>? AND rowid<=? ORDER BY rowid LIMIT ?':c.phase==='commentHistory'?'SELECT sequence AS position,request_key,fingerprint,comment_id,task_id,action,before_json,after_json,created_at FROM comment_events WHERE owner=? AND sequence>? AND sequence<=? ORDER BY sequence LIMIT ?':'SELECT rowid AS position,id,payload,created_at FROM snapshots WHERE owner=? AND rowid>? AND rowid<=? ORDER BY rowid LIMIT ?';
 const rows=await db.prepare(sql).bind(owner,c.after,c.phase==='history'?c.historyHigh:c.phase==='commentHistory'?c.commentHigh:c.snapshotHigh,pageSize+1).all<any>();const items=rows.results.slice(0,pageSize);const more=rows.results.length>pageSize;const phase=c.phase;const next=more?{...c,after:items.at(-1).position}:{...c,phase:phase==='history'?'snapshots':phase==='snapshots'?'commentHistory':'images',after:0};const done=!more&&phase==='commentHistory'&&!c.attachments.length;
 return finish({pageKind:phase,tasks:[],attachments:[],attachmentParts:[],history:phase==='history'?items.map(e=>({requestKey:e.request_key,fingerprint:e.fingerprint,taskId:e.task_id,action:e.action,before:e.before_json?JSON.parse(e.before_json):null,after:JSON.parse(e.after_json),createdAt:e.created_at})):[],commentHistory:phase==='commentHistory'?items.map(e=>({requestKey:e.request_key,fingerprint:e.fingerprint,commentId:e.comment_id,taskId:e.task_id,action:e.action,before:e.before_json?JSON.parse(e.before_json):null,after:JSON.parse(e.after_json),createdAt:e.created_at})):[],snapshots:phase==='snapshots'?items.map(e=>({id:e.id,createdAt:e.created_at,data:JSON.parse(e.payload)})):[]},done?null:next)
}
/** Validate the complete downloaded chain, relationships and every image before any recovery write. */
export async function validateBackup(pages:any[]){
 if(!Array.isArray(pages)||!pages.length)throw new Error('Missing backup pages');const m=pages[0];if(m.format!=='task-board-backup-page'||![2,3].includes(m.version)||m.pageKind!=='manifest')throw new Error('Unsupported backup format');let previous:null|string=null;for(let i=0;i<pages.length;i++){const p=pages[i];if(p.backupId!==m.backupId||p.capturedAt!==m.capturedAt||p.version!==m.version||p.sequence!==i||p.previousChecksum!==previous)throw new Error('Missing, duplicated or mixed backup pages');if(m.version===3&&(p.ownerTag!==m.ownerTag||i>0&&(p.uploadRetries!==undefined||p.storageOwner!==undefined)))throw new Error('Migration ownership or retry metadata changed');const {checksum,nextCursor,...body}=p;if(await hash(stable(body))!==checksum)throw new Error('Backup checksum mismatch');if(p.complete!==(i===pages.length-1))throw new Error('Incomplete backup chain');previous=checksum}if(!pages.at(-1).complete||pages.at(-1).nextCursor!==null)throw new Error('Incomplete backup');
 const tasks=m.tasks.map((t:any)=>taskSchema.parse(t)),history=pages.flatMap(p=>p.history??[]),snapshots=pages.flatMap(p=>p.snapshots??[]),commentHistory=pages.flatMap(p=>p.commentHistory??[]),attachments=m.attachments.map((a:any)=>attachmentSchema.parse(a)),parts=pages.flatMap(p=>p.attachmentParts??[]);const keySchema=z.string().min(8).max(120);const digestSchema=z.string().regex(/^[a-f0-9]{64}$/);const uploadRetries=m.version===3?z.array(uploadRetrySchema).max(100).parse(m.uploadRetries):[];if(m.version===3){digestSchema.parse(m.ownerTag);z.string().min(1).max(200).refine(v=>v===v.trim()&&!/[\u0000-\u001f\u007f]/.test(v)).parse(m.storageOwner);if(await hash(m.storageOwner)!==m.ownerTag)throw new Error('Migration storage owner hash mismatch');if(uploadRetries.length!==attachments.length||uploadRetries.length!==m.counts.uploadRetries||new Set(uploadRetries.map(r=>r.attachmentId)).size!==attachments.length||new Set(uploadRetries.map(r=>r.requestKey)).size!==attachments.length)throw new Error('Migration upload retry count mismatch');for(const a of attachments){const retry=uploadRetries.find(r=>r.attachmentId===a.id);if(!retry||retry.fingerprint!==await hash(stable({taskId:a.taskId,digest:a.sha256,filename:a.filename})))throw new Error('Invalid migration upload fingerprint')}}const historicalComments:any[]=[];const commentsMap=new Map<string,any>();for(const e of commentHistory){keySchema.parse(e.requestKey);digestSchema.parse(e.fingerprint);z.string().datetime().parse(e.createdAt);const c=commentSchema.parse(e.after);const previous=commentsMap.get(c.id);const before=e.before===null?null:commentSchema.parse(e.before);if(stable(before)!==stable(previous??null))throw new Error('Invalid comment before snapshot');historicalComments.push(c);if(before)historicalComments.push(before);if(c.id!==e.commentId||c.taskId!==e.taskId||previous&&c.revision!==previous.revision+1||!previous&&c.revision!==1)throw new Error('Invalid comment revision chain');commentsMap.set(c.id,c)}const comments=[...commentsMap.values()];
 for(const [k,v] of Object.entries({tasks,history,snapshots,comments,commentHistory,attachments,attachmentParts:parts}))if(v.length!==m.counts[k])throw new Error(`Backup count mismatch: ${k}`);
 const taskIds=new Set(tasks.map((t:any)=>t.id));if(taskIds.size!==tasks.length||new Set(attachments.map((a:any)=>a.id)).size!==attachments.length)throw new Error('Duplicate records');const taskVersions=new Map<string,any>();for(const e of history){keySchema.parse(e.requestKey);digestSchema.parse(e.fingerprint);z.string().datetime().parse(e.createdAt);const after=taskSchema.parse(e.after),before=e.before===null?null:taskSchema.parse(e.before);if(!taskIds.has(e.taskId)||after.id!==e.taskId||before&&before.id!==e.taskId||stable(before)!==stable(taskVersions.get(e.taskId)??null)||after.revision!==(before?.revision??0)+1)throw new Error('Invalid history relationship or revision');taskVersions.set(e.taskId,after)}for(const t of tasks)if(stable(t)!==stable(taskVersions.get(t.id)))throw new Error('Task capture does not match history');if(new Set(history.map(e=>e.requestKey)).size!==history.length||new Set(commentHistory.map(e=>e.requestKey)).size!==commentHistory.length||new Set(snapshots.map(e=>e.id)).size!==snapshots.length)throw new Error('Duplicate history or snapshot records');for(const s of snapshots){z.string().max(150).parse(s.id);z.string().datetime().parse(s.createdAt);exportSchema.parse(s.data)}for(const c of historicalComments)if(!taskIds.has(c.taskId)||c.attachmentIds.some((id:string)=>!attachments.some((a:any)=>a.id===id&&a.taskId===c.taskId)))throw new Error('Invalid comment relationship');const blobs=new Map<string,Uint8Array>();let size=0;for(const a of attachments){if(!taskIds.has(a.taskId))throw new Error('Invalid image relationship');const chunks=parts.filter(p=>p.id===a.id);const bytes=new Uint8Array(a.size);let offset=0;for(const p of chunks){const b=unbase64(p.dataBase64);if(p.offset!==offset||offset+b.length>a.size||await hash(b)!==p.sha256)throw new Error('Invalid image part');bytes.set(b,offset);offset+=b.length}if(offset!==a.size||await hash(bytes)!==a.sha256)throw new Error('Incomplete or corrupt image');blobs.set(a.id,bytes);size+=bytes.length}if(size!==m.counts.attachmentBytes||parts.some(p=>!blobs.has(p.id)))throw new Error('Image count mismatch');return {manifest:m,tasks,history,snapshots,comments,commentHistory,attachments,blobs,uploadRetries};
}
