import { z } from 'zod';
export const statuses=['ToDo','InProgress','OnHold','Canceled','Completed','Reference'] as const;
export const labels:Record<string,string>={ToDo:'To do',InProgress:'In progress',OnHold:'On hold',Canceled:'Canceled',Completed:'Completed',Reference:'Reference'};
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>{const d=new Date(s+'T12:00:00Z');return !isNaN(+d)&&d.toISOString().slice(0,10)===s},'Use a valid calendar date');
const timezone=z.string().max(80).refine(v=>{try{new Intl.DateTimeFormat('en',{timeZone:v});return true}catch{return false}},'Use a valid IANA timezone');
export const recurrenceSchema=z.object({frequency:z.literal('monthly'),interval:z.number().int().min(1).max(12),anchorDay:z.number().int().min(1).max(31)}).strict();
export const taskInput=z.object({title:z.string().trim().min(1).max(200),category:z.string().trim().max(80).default('General'),status:z.enum(statuses).default('ToDo'),nextAction:z.string().max(2000).default(''),attention:z.enum(['none','blocked','waiting','review']).default('none'),blocker:z.string().max(2000).default(''),dueDate:date.nullable().default(null),dueTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/,'Use local time HH:MM').nullable().default(null),timezone:timezone.nullable().default(null),recurrence:recurrenceSchema.nullable().default(null),sourceUrl:z.string().max(2000).refine(s=>!s||/^https?:\/\//i.test(s)&&(()=>{try{const u=new URL(s);return !u.username&&!u.password}catch{return false}})(),'Use an http(s) source URL').default(''),sourceChatId:z.string().max(200).default(''),sourceVerifiedAt:z.string().datetime().nullable().default(null),evidenceNote:z.string().max(6000).default(''),sample:z.boolean().default(false)}).strict();
export const taskSchema=taskInput.extend({id:z.string().uuid(),revision:z.number().int().positive(),createdAt:z.string().datetime(),updatedAt:z.string().datetime(),archived:z.boolean()}).strict();
export type Task=z.infer<typeof taskSchema>;export type TaskInput=z.infer<typeof taskInput>;
export function validateTask(v:unknown):TaskInput { const t=taskInput.parse(v);if(t.dueTime&&(!t.dueDate||!t.timezone))throw new Error('A local due time needs a due date and timezone');if(t.recurrence&&(!t.dueDate||!t.timezone))throw new Error('Monthly tasks need a due date and timezone');return t; }
export function nextOccurrence(dueDate:string,rule:z.infer<typeof recurrenceSchema>):string {const [y,m]=dueDate.split('-').map(Number);const d=new Date(Date.UTC(y,m-1+rule.interval,1));const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(Math.min(rule.anchorDay,last)).padStart(2,'0')}`;}
export function inputOf(t:Task):TaskInput {const {id,revision,createdAt,updatedAt,archived,...rest}=t;return rest;}
export const samples:TaskInput[]=[
{title:'SAMPLE · Review maintenance checklist',category:'Operations',status:'ToDo',nextAction:'Review the fictional monthly checklist and note any follow-up',attention:'none',blocker:'',dueDate:'2026-10-29',dueTime:null,timezone:'Etc/UTC',recurrence:{frequency:'monthly',interval:1,anchorDay:29},sourceUrl:'',sourceChatId:'',sourceVerifiedAt:null,evidenceNote:'Synthetic example only. Monthly on the 29th in Etc/UTC; short months use their last day, then return to the 29th.',sample:true},
{title:'SAMPLE · Review technical handoff',category:'Technical',status:'InProgress',nextAction:'Read the proposed change and record a decision',attention:'review',blocker:'Awaiting sign-off from the reviewer',dueDate:null,dueTime:null,timezone:null,recurrence:null,sourceUrl:'',sourceChatId:'',sourceVerifiedAt:null,evidenceNote:'Synthetic example of user review. No real project or conversation is connected.',sample:true},
{title:'SAMPLE · Compare research options',category:'Research',status:'OnHold',nextAction:'Resume when the budget and criteria are known',attention:'waiting',blocker:'Waiting for scope to be clarified',dueDate:null,dueTime:null,timezone:null,recurrence:null,sourceUrl:'',sourceChatId:'',sourceVerifiedAt:null,evidenceNote:'Synthetic example of intentionally paused research.',sample:true}
];
export const exportSchema=z.object({format:z.literal('task-board-pilot'),version:z.literal(1),exportedAt:z.string().datetime(),tasks:z.array(taskSchema).max(100),history:z.array(z.object({taskId:z.string().uuid(),action:z.string().max(50),before:taskSchema.nullable(),after:taskSchema,createdAt:z.string().datetime()}).strict()).max(2000).default([])}).strict();
