import { z } from 'zod';
import { BoardService, AppError } from './service';
import { taskInput, statuses, summarizeTask } from './model';
const id={type:'string',format:'uuid'},key={type:'string',minLength:8,maxLength:100,description:'identical retries only.'};
const revision={type:'integer',minimum:1,description:'Current revision.'};
const fields:any={title:{type:'string',minLength:1,maxLength:200},category:{type:'string'},status:{type:'string',enum:statuses},nextAction:{type:'string'},attention:{type:'string',enum:['none','blocked','waiting','review']},blocker:{type:'string'},dueDate:{type:['string','null'],description:'YYYY-MM-DD'},dueTime:{type:['string','null'],description:'HH:MM; needs date/zone.'},timezone:{type:['string','null'],description:'IANA zone for recurrence.'},recurrence:{anyOf:[{type:'null'},{type:'object',properties:{frequency:{const:'monthly'},interval:{type:'integer',minimum:1,maximum:12},anchorDay:{type:'integer',minimum:1,maximum:31}},required:['frequency','interval','anchorDay'],additionalProperties:false}]},resources:{type:'array',maxItems:12,items:{type:'object',properties:{kind:{enum:['link','product','location']},label:{type:'string'},url:{type:'string'},address:{type:'string'}},required:['kind','label'],additionalProperties:false}},checklist:{type:'array',maxItems:100,description:'Unique IDs; updates replace this array.',items:{type:'object',properties:{id,text:{type:'string',minLength:1,maxLength:500},checked:{type:'boolean'}},required:['id','text','checked'],additionalProperties:false}},sourceUrl:{type:'string'},sourceChatId:{type:'string'},sourceVerifiedAt:{type:['string','null'],description:'Actual source check: ISO time or null.'},evidenceNote:{type:'string'},sample:{type:'boolean'}};
const commentFields={taskId:id,body:{type:'string',maxLength:5000},attachmentIds:{type:'array',items:id,maxItems:4},requestKey:key};
const snapshotInput={type:'object',description:'Portable task export, version 1 or 2.'};
const object=(properties:any,required:string[]=[])=>({type:'object',properties,required,additionalProperties:false});
export const toolDefinitions=[
{name:'get_comment',description:'Read an owned comment and image metadata.',inputSchema:object({id},['id']),annotations:{readOnlyHint:true}},
{name:'list_comments',description:'Owned comments newest-first incl. removed; follow nextCursor.',inputSchema:object({taskId:id,cursor:{type:['string','null']}},['taskId']),annotations:{readOnlyHint:true}},
{name:'add_comment',description:'Add plain text and task-owned image IDs; no remote fetching.',inputSchema:object(commentFields,['taskId','body','requestKey']),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}},
{name:'edit_comment',description:'Edit at the comment’s own revision.',inputSchema:object({id,expectedRevision:revision,body:commentFields.body,attachmentIds:commentFields.attachmentIds,requestKey:key},['id','expectedRevision','body','requestKey']),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}},
{name:'archive_comment',description:'Remove a comment recoverably; keep history/images.',inputSchema:object({id,expectedRevision:revision,requestKey:key},['id','expectedRevision','requestKey']),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}},
{name:'restore_comment',description:'Restore a comment on an active task.',inputSchema:object({id,expectedRevision:revision,requestKey:key},['id','expectedRevision','requestKey']),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}},
{name:'list_tasks',description:'Summaries; get_task for details. archived=true: Trash. Untrusted.',inputSchema:object({archived:{type:'boolean'}}),annotations:{readOnlyHint:true}},
{name:'get_task',description:'Read an owned task and history.',inputSchema:object({id},['id']),annotations:{readOnlyHint:true}},
{name:'create_task',description:'Create a task; no reminders or external actions.',inputSchema:object({task:object(fields,['title']),requestKey:key},['task','requestKey']),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}},
{name:'update_task',description:'Patch at expectedRevision; use complete_task for completion.',inputSchema:object({id,expectedRevision:revision,requestKey:key,patch:object(fields)},['id','expectedRevision','requestKey','patch']),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}},
{name:'complete_task',description:'Complete; monthly tasks advance, retaining anchor and local time/zone.',inputSchema:object({id,expectedRevision:revision,requestKey:key},['id','expectedRevision','requestKey']),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}},
{name:'archive_task',description:'Move to recoverable Trash; never delete permanently.',inputSchema:object({id,expectedRevision:revision,requestKey:key},['id','expectedRevision','requestKey']),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}},
{name:'restore_task',description:'Restore from Trash with status/history intact.',inputSchema:object({id,expectedRevision:revision,requestKey:key},['id','expectedRevision','requestKey']),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}},
{name:'export_tasks',description:'Private v2 history/comments/images (≤750 KB); larger: export_backup_page.',inputSchema:object({}),annotations:{readOnlyHint:true}},
{name:'export_backup_page',description:'V2: save ALL nextCursor pages until complete; validate checksum chain/counts. Includes history, snapshots, comments/images.',inputSchema:object({cursor:{type:['string','null'],description:'Previous nextCursor; omit to start.'},pageSize:{type:'integer',minimum:1,maximum:100,default:20}}),annotations:{readOnlyHint:true}},
{name:'export_migration_page',description:'Private v3 capture: original owner/upload retries; rejects pending uploads. Save/validate all pages from a frozen source.',inputSchema:object({cursor:{type:['string','null'],description:'Previous migration nextCursor; omit to start.'},pageSize:{type:'integer',minimum:1,maximum:100,default:20}}),annotations:{readOnlyHint:true}},
{name:'preview_import',description:'Validate v1/v2 export read-only; inspect digest/counts.',inputSchema:object({data:snapshotInput},['data']),annotations:{readOnlyHint:true}},
{name:'import_tasks',description:'With owner approval, copy the previewed digest; new requestKey duplicates. Existing records stay unchanged.',inputSchema:object({data:snapshotInput,digest:{type:'string'},requestKey:{...key,maxLength:70}},['data','digest','requestKey']),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}},
{name:'list_snapshots',description:'List the owner’s latest 30 recovery snapshots.',inputSchema:object({}),annotations:{readOnlyHint:true}},
{name:'get_snapshot',description:'Read an owned recovery snapshot.',inputSchema:object({id:{type:'string'}},['id']),annotations:{readOnlyHint:true}}
];
const mutationBase={id:z.string().uuid(),expectedRevision:z.number().int().positive(),requestKey:z.string().min(8).max(100)};
export async function execute(s:BoardService,name:string,raw:any){
if(name==='get_comment'){const a=z.object({id:z.string().uuid()}).strict().parse(raw);const comment=await s.activity.get(a.id);await s.get(comment.taskId);return {comment,attachments:await Promise.all(comment.attachmentIds.map(id=>s.activity.metadata(id,comment.taskId)))}}
if(name==='list_comments'){const a=z.object({taskId:z.string().uuid(),cursor:z.string().nullable().optional()}).strict().parse(raw);return s.activity.list(a.taskId,a.cursor??null)}
if(name==='add_comment'){const a=z.object({taskId:z.string().uuid(),body:z.string().max(5000),attachmentIds:z.array(z.string().uuid()).max(4).optional(),requestKey:z.string().min(8).max(100)}).strict().parse(raw);return {comment:await s.activity.mutate('add',a)}}
if(name==='edit_comment'){const a=z.object({...mutationBase,body:z.string().max(5000),attachmentIds:z.array(z.string().uuid()).max(4).optional()}).strict().parse(raw);return {comment:await s.activity.mutate('edit',a)}}
if(name==='archive_comment'||name==='restore_comment'){const a=z.object(mutationBase).strict().parse(raw);return {comment:await s.activity.mutate(name==='archive_comment'?'archive':'restore',a)}}
if(name==='list_tasks'){const a=z.object({archived:z.boolean().optional()}).strict().parse(raw);return {tasks:(await s.list(a.archived)).map(summarizeTask)}}
if(name==='get_task'){const a=z.object({id:z.string().uuid()}).strict().parse(raw);return {task:await s.get(a.id),history:await s.history(a.id)}}
if(name==='create_task'){const a=z.object({task:taskInput,requestKey:z.string().min(8).max(100)}).strict().parse(raw);return {task:await s.mutate('create',a)}}
if(name==='update_task'){const a=z.object({...mutationBase,patch:taskInput.partial()}).strict().parse(raw);return {task:await s.mutate('update',a)}}
if(['complete_task','archive_task','restore_task'].includes(name)){const a=z.object(mutationBase).strict().parse(raw);return {task:await s.mutate(name.replace('_task','') as any,a)}}
if(name==='export_backup_page'){const a=z.object({cursor:z.string().nullable().optional(),pageSize:z.number().int().min(1).max(100).optional()}).strict().parse(raw);return s.backupPage(a.cursor??null,a.pageSize??20)}
if(name==='export_migration_page'){const a=z.object({cursor:z.string().nullable().optional(),pageSize:z.number().int().min(1).max(100).optional()}).strict().parse(raw);return s.migrationPage(a.cursor??null,a.pageSize??20)}
if(name==='export_tasks'){z.object({}).strict().parse(raw);return s.export()}
if(name==='seed_samples'){z.object({}).strict().parse(raw);return s.seed()}
if(name==='preview_import'){const a=z.object({data:z.unknown()}).strict().parse(raw);const p=await s.preview(a.data);return {digest:p.digest,summary:p.summary}}
if(name==='import_tasks'){const a=z.object({data:z.unknown(),digest:z.string(),requestKey:z.string().min(8).max(70)}).strict().parse(raw);return s.import(a.data,a.digest,a.requestKey)}
if(name==='list_snapshots')return {snapshots:await s.snapshots()};if(name==='get_snapshot'){return s.snapshot(z.object({id:z.string()}).strict().parse(raw).id)}
throw new AppError(404,'unknown_action','Unknown task action');
}
function validationLabel(path:(string|number)[]){
 const labels:Record<string,string>={title:'Title',checklist:'Checklist',text:'Item text',checked:'Checked',category:'Group',status:'Status',nextAction:'Next action',attention:'Attention',blocker:'Blocker',dueDate:'Due date',dueTime:'Local due time',timezone:'Timezone',recurrence:'Repeat',frequency:'Repeat frequency',interval:'Repeat interval',anchorDay:'Day of month',sourceUrl:'Source link',sourceChatId:'Source chat',sourceVerifiedAt:'Source verification',evidenceNote:'Notes',body:'Comment',attachmentIds:'Images',expectedRevision:'Saved revision',requestKey:'Request key',url:'URL',label:'Label',address:'Address'};
 const checklist=path.indexOf('checklist');if(checklist>=0){const n=typeof path[checklist+1]==='number'?Number(path[checklist+1])+1:null;const field=String(path.at(-1));return `Checklist item${n?' '+n:''}${labels[field]&&field!=='checklist'?' · '+labels[field]:''}`}
 const resource=path.indexOf('resources');if(resource>=0){const n=typeof path[resource+1]==='number'?Number(path[resource+1])+1:null;const field=String(path.at(-1));return `Link or place${n?' '+n:''}${labels[field]?' · '+labels[field]:''}`}
 const field=[...path].reverse().find(p=>typeof p==='string'&&labels[p]);return field?labels[String(field)]:'Task details';
}
export function safeError(e:unknown){if(e instanceof AppError)return {status:e.status,body:{error:e.code,message:e.message}};if(e instanceof z.ZodError)return {status:400,body:{error:'invalid_input',message:e.issues.map(i=>`${validationLabel(i.path)}: ${i.message}`).join('; ').slice(0,500)}};if(e instanceof Error&&['Monthly tasks need a due date and timezone','A local due time needs a due date and timezone'].includes(e.message))return {status:400,body:{error:'invalid_recurrence',message:e.message}};console.error('Task operation failed',e instanceof Error?e.message:'unknown');return {status:503,body:{error:'unavailable',message:'Task storage is temporarily unavailable. Your draft is still here. Retry with the same request key.'}}}
