// Local/offline recovery only. Never connects to the live Site or overwrites an existing destination.
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,writeFileSync,readdirSync,existsSync,mkdirSync,renameSync,openSync,closeSync,fsyncSync,lstatSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {validateBackup} from '../lib/backup.ts';
import {normalizePng} from '../lib/image.ts';
import {hash,stable} from '../lib/safety.ts';
function atomicState(filename,value){const next=filename+'.next';const fd=openSync(next,'w',0o600);try{writeFileSync(fd,JSON.stringify(value));fsyncSync(fd)}finally{closeSync(fd)}renameSync(next,filename);const directory=openSync(path.dirname(filename),'r');try{fsyncSync(directory)}finally{closeSync(directory)}}
export async function recoverBackup(pages,destination,owner){
 if(typeof owner!=='string'||!owner.trim())throw new Error('An explicit recovery owner is required');
 const data=await validateBackup(pages);for(const a of data.attachments){const image=await normalizePng(data.blobs.get(a.id));if(image.width!==a.width||image.height!==a.height)throw new Error('Invalid image dimensions')}
 const checksum=await hash(stable(pages)),ownerHash=await hash(owner),statePath=path.join(destination,'recovery-state.json');let existing=null;
 if(existsSync(destination)){const info=lstatSync(destination);if(!info.isDirectory()||info.isSymbolicLink()||(info.mode&0o077)!==0)throw new Error('Recovery destination must be a private directory accessible only to its owner');if(!existsSync(statePath)){const entries=readdirSync(destination);if(entries.length===1&&entries[0]==='recovery-state.json.next'){let candidate;try{candidate=JSON.parse(readFileSync(statePath+'.next','utf8'))}catch{throw new Error('Interrupted state file is invalid; no records were overwritten')}if(candidate.checksum!==checksum||candidate.ownerHash!==ownerHash)throw new Error('Destination belongs to a different recovery');renameSync(statePath+'.next',statePath)}else if(entries.length)throw new Error('Destination exists and is not this recovery; refusing to overwrite it')}if(existsSync(statePath))existing=JSON.parse(readFileSync(statePath,'utf8'));if(existing&&(existing.checksum!==checksum||existing.ownerHash!==ownerHash))throw new Error('Destination belongs to a different recovery')}else mkdirSync(destination,{recursive:true,mode:0o700});
 if(!existing)atomicState(statePath,{version:2,checksum,ownerHash,complete:false});
 const objectDirectory=path.join(destination,'objects',ownerHash);mkdirSync(objectDirectory,{recursive:true,mode:0o700});for(const a of data.attachments){const filename=path.join(objectDirectory,a.id+'.png');if(existsSync(filename)){if(await hash(new Uint8Array(readFileSync(filename)))!==a.sha256)throw new Error('Existing recovery image differs; refusing to overwrite it')}else{writeFileSync(filename+'.partial',data.blobs.get(a.id),{mode:0o600});renameSync(filename+'.partial',filename)}}
 const dbPath=path.join(destination,'tasks.sqlite'),fresh=!existsSync(dbPath);if(fresh)writeFileSync(dbPath,'',{mode:0o600,flag:'wx'});else if(lstatSync(dbPath).isSymbolicLink())throw new Error('Recovery database must not be a symbolic link');const db=new DatabaseSync(dbPath);try{if(fresh||db.prepare("SELECT COUNT(*) AS n FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").get().n===0){db.exec('BEGIN');const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');for(const migration of readdirSync(path.join(root,'drizzle')).filter(x=>x.endsWith('.sql')).sort())db.exec(readFileSync(path.join(root,'drizzle',migration),'utf8'));db.exec('CREATE TABLE recovery_marker(checksum TEXT PRIMARY KEY, owner_hash TEXT NOT NULL)');db.exec('COMMIT')}
 const marker=db.prepare('SELECT checksum,owner_hash FROM recovery_marker').get();if(marker&&(marker.checksum!==checksum||marker.owner_hash!==ownerHash))throw new Error('Recovery marker mismatch');if(!marker){for(const table of ['tasks','task_events','comments','comment_events','attachments','snapshots'])if(db.prepare(`SELECT COUNT(*) AS n FROM ${table}`).get().n)throw new Error('Recovery database is not empty; refusing to replace records');db.exec('BEGIN');try{
 for(const task of data.tasks){const last=data.history.filter(e=>e.taskId===task.id).at(-1);db.prepare('INSERT INTO tasks(owner,id,payload,status,archived,revision,updated_at,last_mutation) VALUES(?,?,?,?,?,?,?,?)').run(owner,task.id,JSON.stringify(task),task.status,Number(task.archived),task.revision,task.updatedAt,last.requestKey)}
 for(const e of data.history)db.prepare('INSERT INTO task_events(owner,request_key,fingerprint,task_id,action,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?,?)').run(owner,e.requestKey,e.fingerprint,e.taskId,e.action,e.before?JSON.stringify(e.before):null,JSON.stringify(e.after),e.createdAt);
 for(const s of data.snapshots)db.prepare('INSERT INTO snapshots(owner,id,payload,created_at) VALUES(?,?,?,?)').run(owner,s.id,JSON.stringify(s.data),s.createdAt);
 for(const c of data.comments){const last=data.commentHistory.filter(e=>e.commentId===c.id).at(-1);db.prepare('INSERT INTO comments(owner,id,task_id,payload,revision,last_mutation) VALUES(?,?,?,?,?,?)').run(owner,c.id,c.taskId,JSON.stringify(c),c.revision,last.requestKey)}
 for(const e of data.commentHistory)db.prepare('INSERT INTO comment_events(owner,request_key,fingerprint,comment_id,task_id,action,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(owner,e.requestKey,e.fingerprint,e.commentId,e.taskId,e.action,e.before?JSON.stringify(e.before):null,JSON.stringify(e.after),e.createdAt);
 for(const a of data.attachments)db.prepare('INSERT INTO attachments(owner,id,task_id,payload,object_key,request_key,fingerprint,ready,size) VALUES(?,?,?,?,?,?,?,?,?)').run(owner,a.id,a.taskId,JSON.stringify(a),`images/${ownerHash}/${a.id}`,'recovered:'+a.id,a.sha256,1,a.size);
 db.prepare('INSERT INTO recovery_marker(checksum,owner_hash) VALUES(?,?)').run(checksum,ownerHash);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}

 const expected={
 tasks:data.tasks.map(t=>({owner,id:t.id,payload:JSON.stringify(t),status:t.status,archived:Number(t.archived),revision:t.revision,updated_at:t.updatedAt,last_mutation:data.history.filter(e=>e.taskId===t.id).at(-1).requestKey})),
 task_events:data.history.map(e=>({owner,request_key:e.requestKey,fingerprint:e.fingerprint,task_id:e.taskId,action:e.action,before_json:e.before?JSON.stringify(e.before):null,after_json:JSON.stringify(e.after),created_at:e.createdAt})),
 snapshots:data.snapshots.map(v=>({owner,id:v.id,payload:JSON.stringify(v.data),created_at:v.createdAt})),
 comments:data.comments.map(c=>({owner,id:c.id,task_id:c.taskId,payload:JSON.stringify(c),revision:c.revision,last_mutation:data.commentHistory.filter(e=>e.commentId===c.id).at(-1).requestKey})),
 comment_events:data.commentHistory.map(e=>({owner,request_key:e.requestKey,fingerprint:e.fingerprint,comment_id:e.commentId,task_id:e.taskId,action:e.action,before_json:e.before?JSON.stringify(e.before):null,after_json:JSON.stringify(e.after),created_at:e.createdAt})),
 attachments:data.attachments.map(a=>({owner,id:a.id,task_id:a.taskId,payload:JSON.stringify(a),object_key:`images/${ownerHash}/${a.id}`,request_key:'recovered:'+a.id,fingerprint:a.sha256,ready:1,size:a.size}))
 };
 const columns={tasks:'owner,id,payload,status,archived,revision,updated_at,last_mutation',task_events:'owner,request_key,fingerprint,task_id,action,before_json,after_json,created_at',snapshots:'owner,id,payload,created_at',comments:'owner,id,task_id,payload,revision,last_mutation',comment_events:'owner,request_key,fingerprint,comment_id,task_id,action,before_json,after_json,created_at',attachments:'owner,id,task_id,payload,object_key,request_key,fingerprint,ready,size'};
 for(const [table,records] of Object.entries(expected)){const actual=db.prepare(`SELECT ${columns[table]} FROM ${table}`).all();const canonical=rows=>rows.map(stable).sort();if(stable(canonical(actual))!==stable(canonical(records)))throw new Error(`Recovered ${table} differ from the verified backup; refusing to claim completion`)}
 }finally{db.close()}
 atomicState(statePath,{version:2,checksum,ownerHash,complete:true,counts:data.manifest.counts});return {database:dbPath,objects:objectDirectory,counts:data.manifest.counts,complete:true};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const [file,destination,owner]=process.argv.slice(2);if(!file||!destination||!owner)throw new Error('Usage: recover-backup.mjs BACKUP.json EMPTY_DESTINATION OWNER_ID');const value=JSON.parse(readFileSync(file,'utf8'));console.log(JSON.stringify(await recoverBackup(value.pages??value,path.resolve(destination),owner)))}
